# Generated by Django 5.2.6 on 2025-09-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_image', models.ImageField(upload_to='problems/')),
                ('answer_image', models.ImageField(upload_to='answers/')),
                ('student_image', models.ImageField(upload_to='students/')),
                ('gpt_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
