# Generated by Django 5.2.6 on 2025-10-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionanalysis',
            name='overlay_image',
            field=models.ImageField(blank=True, null=True, upload_to='overlays/'),
        ),
    ]
